[dependencies]
pingr = "0.5.0"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
structopt = "0.3"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"